walker2d:
  env_id: Walker2d-v5
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.999995
  epsilon_min: 0.05
  network_sync_rate: 1000
  learning_rate: 0.0001
  discount_factor_g: 0.99
  forward_reward_weight: 1.0
  ctrl_cost_weight: 0.001
  healthy_reward: 1.0